defmodule Apino.Schema.Property do
  use Ecto.Schema
  import Ecto.Changeset


  schema "apino_properties" do
    field :field_name, :string
    field :is_autogenerated, :boolean, default: false
    field :is_binary, :boolean, default: false
    field :is_primary, :boolean, default: false
    field :is_unique, :boolean, default: false
    field :label, :string
    field :name, :string
    field :type, :string, default: "string"
    field :status, :string
    field :default_value, :string, default: ""
    field :options, :map
    belongs_to :entity, Apino.Schema.Entity

    timestamps()
  end

  @doc false
  def changeset(property, attrs) do
    property
    |> cast(attrs, [:name, :field_name, :label, :status, :type, :options, :default_value, :is_primary, :is_binary, :is_autogenerated, :is_unique])
    |> validate_required([:name, :field_name, :label, :status, :type])
  end
  @doc false
  def change_entity(cs, entity), do: cs |> put_assoc(:entity, entity)
end
