defmodule ApinoWeb.PropertyView do
  use ApinoWeb, :view
  alias ApinoWeb.PropertyView

  def render("index.json", %{properties: properties}) do
    %{data: render_many(properties, PropertyView, "property.json")}
  end

  def render("show.json", %{property: property}) do
    %{data: render_one(property, PropertyView, "property.json")}
  end

  def render("property.json", %{property: property}) do
    %{id: property.id,
      name: property.name,
      field_name: property.field_name,
      label: property.label,
      status: property.status,
      type: property.type,
      default_value: property.default_value,
      options: property.options,
      is_primary: property.is_primary,
      is_binary: property.is_binary,
      is_autogenerated: property.is_autogenerated,
      is_unique: property.is_unique}
  end
end
