defmodule Apino.Repo.Migrations.CreateApinoProperties do
  use Ecto.Migration

  def change do
    create table(:apino_properties) do
      add :name, :string
      add :field_name, :string
      add :label, :string
      add :status, :string
      add :type, :string, default: "string"
      add :default_value, :string, default: ""
      add :options, :map
      add :is_primary, :boolean, default: false, null: false
      add :is_binary, :boolean, default: false, null: false
      add :is_autogenerated, :boolean, default: false, null: false
      add :is_unique, :boolean, default: false, null: false
      add :entity_id, references(:apino_entities, on_delete: :delete_all)

      timestamps()
    end

    create index(:apino_properties, [:entity_id])
  end
end
